language: node_js

node_js:
  - 'stable'

sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install
  - (cd e2e ; npm install)

script:
  - npm run e2e
